// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreenshot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CaptureScreenshot'](arg1, arg2, arg3, arg4);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteHistoryItem(arg1) {
  return window['go']['main']['App']['DeleteHistoryItem'](arg1);
}

export function ExportHistoryToText(arg1) {
  return window['go']['main']['App']['ExportHistoryToText'](arg1);
}

export function ExtractTextFromScreenshot(arg1) {
  return window['go']['main']['App']['ExtractTextFromScreenshot'](arg1);
}

export function GenerateMeetingSummary(arg1) {
  return window['go']['main']['App']['GenerateMeetingSummary'](arg1);
}

export function GetAllHistory() {
  return window['go']['main']['App']['GetAllHistory']();
}

export function GetDPIScale() {
  return window['go']['main']['App']['GetDPIScale']();
}

export function GetLastScreenshotPath() {
  return window['go']['main']['App']['GetLastScreenshotPath']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetRecentHistory(arg1) {
  return window['go']['main']['App']['GetRecentHistory'](arg1);
}

export function GetRecordingDuration() {
  return window['go']['main']['App']['GetRecordingDuration']();
}

export function GetScreenSize() {
  return window['go']['main']['App']['GetScreenSize']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTodayHistory() {
  return window['go']['main']['App']['GetTodayHistory']();
}

export function GetWindowPosition() {
  return window['go']['main']['App']['GetWindowPosition']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function OpenDevTools() {
  return window['go']['main']['App']['OpenDevTools']();
}

export function OpenRecordingFolder() {
  return window['go']['main']['App']['OpenRecordingFolder']();
}

export function PositionWindowAt(arg1, arg2) {
  return window['go']['main']['App']['PositionWindowAt'](arg1, arg2);
}

export function QueryLLM(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryLLM'](arg1, arg2, arg3);
}

export function QueryLLMWithWebSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryLLMWithWebSearch'](arg1, arg2, arg3);
}

export function ReadDocumentFile(arg1) {
  return window['go']['main']['App']['ReadDocumentFile'](arg1);
}

export function ReadScreenshotAsBase64(arg1) {
  return window['go']['main']['App']['ReadScreenshotAsBase64'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectAudioFile() {
  return window['go']['main']['App']['SelectAudioFile']();
}

export function SelectDocumentFiles() {
  return window['go']['main']['App']['SelectDocumentFiles']();
}

export function SetWindowPosition(arg1, arg2) {
  return window['go']['main']['App']['SetWindowPosition'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function TriggerScreenshot() {
  return window['go']['main']['App']['TriggerScreenshot']();
}
