// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreenshot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CaptureScreenshot'](arg1, arg2, arg3, arg4);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function QueryLLM(arg1, arg2) {
  return window['go']['main']['App']['QueryLLM'](arg1, arg2);
}

export function RegisterGlobalHotkey() {
  return window['go']['main']['App']['RegisterGlobalHotkey']();
}
