// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CaptureScreenshot(arg1:number,arg2:number,arg3:number,arg4:number):Promise<string>;

export function GetDPIScale():Promise<number>;

export function GetLastScreenshotPath():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetScreenSize():Promise<number|number>;

export function GetSettings():Promise<main.AppSettings>;

export function GetWindowPosition():Promise<number|number>;

export function HideWindow():Promise<void>;

export function OpenDevTools():Promise<void>;

export function PositionWindowAt(arg1:number,arg2:number):Promise<void>;

export function QueryLLM(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SetWindowPosition(arg1:number,arg2:number):Promise<void>;

export function ShowWindow():Promise<void>;

export function TriggerScreenshot():Promise<void>;
